TEST QUERY SCRIPT

UPDATE STATEMENT-----------------------------------------

UPDATE BRANCH
SET MANAGERLAST = 'TOM'
WHERE MANAGERLAST = 'MARLK';

UPDATE PERSON
SET FIRSTNAME = 'TASNEEM'
WHERE FIRSTNAME = 'ROYALS';

UPDATE SAVINGS
SET INTERESTRATE= '2.99'
WHERE INTERESTRATE= ='5.99';

UPDATE AUTO
SET DOWNPAYMENT= 7000
WHERE DOWNPAYMENT= = 5070;

UPDATE STUDENT
SET ESTGRADUATIONDATE= '15-DEC-2018'
WHERE ESTGRADUATIONDATE= '18-MAR-2018';



SELECT STATEMENTS-------------

SELECT STUDENT.SCHOOLNAME,STUDENT.MAJOR
FROM STUDENT,LOAN
WHERE STUDENT.SLOANNO = LOAN.LOANNO;


SELECT BRANCH.BRANCHNAME,BRANCH.MANAGERFIRST, MANAGERLAST,
BANKINGLOCATION.NUMBERSTREET
FROM BRANCH,BANKINGLOCATION
WHERE BRANCH.BBLOCATIONID = BANKINGLOCATION.BLOCATIONID;


SELECT PERSON.FIRSTNAME,PERSON.LASTNAME,CUSTOMER.NUMBERSTREET
FROM CUSTOMER,PERSON
WHERE CUSTOMER.CUSTOMERID = PERSON.PCUSTOMERID;


SELECT CUSTOMER.CITY,BANKINGTRANSACTION.TRANSACTIONDATE
FROM CUSTOMER,BANKINGTRANSACTION
WHERE CUSTOMER.CUSTOMERID = BANKINGTRANSACTION.CUSTOMERID;


SELECT ACCOUNT.PRESENTBALANCE, SAVINGS.INTERESTRATE
FROM ACCOUNT,SAVINGS
WHERE ACCOUNT.ACCOUNTNO = SAVINGS.SACCOUNTNO;

-----------------------------------------


DELETE STATEMENTS-----------------

DELETE FROM BENEFICIARY
WHERE LASTNAME = 'ALASKA';

DELETE FROM ACCOUNTSTATUS
WHERE ACCOUNTSTATUSDESC = 'CLOSED';

DELETE FROM VEHICLETYPE
WHERE VEHICLETYPEDESC = 'COMMERCIAL VEHICLE';

DELETE FROM LOANTERM
WHERE LOANTERMDESC = '8 YEARS';

DELETE FROM BANKER
WHERE BANKERID= '34555';